# Generated by Django 5.0.7 on 2024-08-20 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("pid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("main_image", models.ImageField(upload_to="products/images/")),
                ("second_image", models.ImageField(upload_to="products/images/")),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("mrp", models.DecimalField(decimal_places=2, max_digits=10)),
                ("model", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=50)),
                ("brand", models.CharField(max_length=30)),
                ("screen", models.CharField(max_length=100)),
                ("processor", models.CharField(max_length=100)),
                ("ssd", models.CharField(max_length=50)),
                ("ram", models.CharField(max_length=50)),
                ("ram_type", models.CharField(max_length=50)),
                ("clock_speed", models.CharField(max_length=50)),
                ("gpu", models.CharField(max_length=100)),
                ("disk_drive", models.CharField(max_length=50)),
                ("cam", models.BooleanField()),
                ("fingerprint", models.BooleanField()),
                ("keyboard", models.CharField(max_length=50)),
                ("stock", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("oid", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.PositiveBigIntegerField()),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.customuser",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
            ],
        ),
    ]
