# Generated by Django 5.0.7 on 2024-08-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_order_order_date_remove_order_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.AddField(
            model_name="order",
            name="billing_address",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.CharField(default="cash on delivery", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(default="1234567890", max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.CharField(default="test address", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="zipcode",
            field=models.CharField(default=12345, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
