# Generated by Django 5.0.7 on 2024-08-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_cartitem_cart_remove_cartitem_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Everyday", "Everyday Laptop"),
                    ("Gaming", "Gaming Laptop"),
                    ("Thin_Light", "Thin and Light Laptop"),
                    ("Multitasking", "Multitasking Laptop"),
                    ("Developer", "Developer Laptop"),
                ],
                default="Everyday",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
