# Generated by Django 5.0.7 on 2024-08-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_product_stock_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
