# Generated by Django 5.0.7 on 2024-08-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("admin", "Admin"), ("customer", "Customer")],
                default="customer",
                max_length=10,
            ),
        ),
    ]
